name: Snake
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master"]}
jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            github-snake-dark.svg?palette=github-dark
